openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /simulations/execution/{eID}/:
    get:
      operationId: retrievehttp_execution
      description: 'Get the status of a specific execution given by the eID specified into the parameters'
      parameters:
      - name: eID
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
           description: 'Get the status back of the execution'
          example: '{"message":"eID: f274dcfc-c20c-4784-8d63-eb73693fb365,name: test,jobID: 0,user: bsc19518,nodes: 4,status: INITIALIZING,autorestart: False,time: 00:00:00;"}'
      tags:
      - simulations
    put:
      operationId: updatehttp_execution
      description: 'Stop or restart a specific execution given by the eID specified into the parameters and given stop or start as status parameter'
      parameters:
      - name: eID
        in: path
        required: true
        description: ''
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - simulations
    delete:
      operationId: destroyhttp_execution
      description: 'Delete a specific execution given by the eID specified into the parameters'
      parameters:
      - name: eID
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '204':
          description: '{'message': 'Execution deleted successfully'}'
      tags:
      - simulations
  /simulations/:
    post:
      operationId: createrun_simulation
      description: 'Confirm that the simulation started successfully and gives back the unique ID of the new simulation.'
      parameters: []
      requestBody:
        content:
          multipart/form-data:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: '{"message":"Simulation started successfully! ","execution_id":"xxxxxxx-xxxx-xxxxx-xxxx-xxxxxxx"}'
      tags:
      - simulations
