# Generated by Django 4.1.7 on 2023-04-03 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('samplerName', models.CharField(choices=[('morris', 'Morris'), ('saltelli', 'Saltelli')], default='morris', max_length=255)),
                ('samplerParameters', models.CharField(blank=True, max_length=255)),
                ('simulation', models.CharField(choices=[('morris', 'Morris'), ('saltelli', 'Saltelli')], default='alya', max_length=255)),
                ('sensitivityType', models.CharField(choices=[('morris', 'Morris'), ('saltelli', 'Saltelli')], default='morris', max_length=255)),
                ('sensitivityOutput', models.CharField(blank=True, max_length=255)),
                ('wdir', models.CharField(blank=True, max_length=500)),
                ('templateFile', models.CharField(blank=True, max_length=255)),
                ('output_folder', models.CharField(blank=True, max_length=255)),
                ('numVarproblem', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default='3')),
                ('variablesSampler', models.CharField(blank=True, max_length=255)),
                ('variablesFixed', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Key_Gen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_nord3', models.CharField(max_length=255)),
                ('public_key', models.CharField(max_length=255)),
                ('private_key', models.CharField(max_length=255)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobID', models.IntegerField()),
                ('user', models.CharField(max_length=255)),
                ('nodes', models.IntegerField()),
                ('status', models.CharField(max_length=255)),
                ('time', models.TimeField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
