# Generated by Django 4.1.7 on 2023-07-19 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('samplerName', models.CharField(choices=[('morris', 'Morris'), ('saltelli', 'Saltelli')], default='morris', max_length=255)),
                ('samplerParameters', models.CharField(max_length=255)),
                ('simulation', models.CharField(choices=[('alya', 'Alya')], default='alya', max_length=255)),
                ('mesh', models.CharField(max_length=255)),
                ('templateSim', models.CharField(max_length=255)),
                ('sensitivity', models.CharField(choices=[('morris', 'Morris'), ('saltelli', 'Saltelli')], default='morris', max_length=255)),
                ('sensitivityOutput', models.CharField(max_length=255)),
                ('outputs', models.CharField(max_length=255)),
                ('numVarproblem', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default='3')),
                ('variablesSampler', models.CharField(max_length=500)),
                ('variablesFixed', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('fqdn', models.CharField(max_length=255)),
                ('wdir', models.CharField(max_length=2048)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='Key_Gen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.CharField(max_length=3000)),
                ('private_key', models.CharField(max_length=3000)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.machine')),
            ],
        ),
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobID', models.IntegerField()),
                ('user', models.CharField(max_length=255)),
                ('nodes', models.IntegerField()),
                ('status', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('execution_time', models.IntegerField()),
                ('qos', models.CharField(max_length=255)),
                ('name_workflow', models.CharField(max_length=255)),
                ('checkpoint', models.IntegerField(default=0)),
                ('wdir', models.CharField(max_length=500)),
                ('workflow_path', models.CharField(max_length=500)),
                ('autorestart', models.BooleanField(default=False)),
                ('name_sim', models.CharField(max_length=255)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('idConn_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Disconnect', 'Disconnect'), ('Timeout', 'Timeout')], default='Disconnect', max_length=30)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
