# Generated by Django 4.1.7 on 2023-04-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key_gen',
            name='private_key',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='key_gen',
            name='public_key',
            field=models.CharField(max_length=2048),
        ),
    ]
