# Generated by Django 4.1.7 on 2023-04-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_key_gen_private_key_alter_key_gen_public_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execution',
            name='time',
            field=models.CharField(max_length=255),
        ),
    ]
