# Generated by Django 4.1.7 on 2023-09-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_execution_machine'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='installDir',
            field=models.CharField(default='your_default_value', max_length=2048),
        ),
    ]
