# Generated by Django 4.1.7 on 2023-04-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_execution_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='wdir',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
    ]
