# Generated by Django 4.1.7 on 2023-11-06 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_api_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='api_user',
        ),
    ]
