# Generated by Django 4.1.7 on 2023-09-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_machine_installdir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='installDir',
            field=models.CharField(max_length=2048),
        ),
    ]
