# Generated by Django 4.1.7 on 2023-04-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_execution_wdir'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='workflow_path',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
    ]
