# Generated by Django 4.1.7 on 2023-04-19 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_execution_workflow_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='key_gen',
            old_name='user_nord3',
            new_name='user',
        ),
        migrations.AddField(
            model_name='key_gen',
            name='machine',
            field=models.CharField(choices=[('Nord3', 'Nord3'), ('MareNostrum', 'MareNostrum')], default='Nord3', max_length=255),
        ),
    ]
