# Generated by Django 4.1.7 on 2024-02-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_execution_checkpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execution',
            name='checkpoint',
            field=models.IntegerField(default=0),
        ),
    ]
