# Generated by Django 4.1.7 on 2023-04-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_user_nord3_key_gen_user_key_gen_machine'),
    ]

    operations = [
        migrations.AddField(
            model_name='key_gen',
            name='wdir',
            field=models.CharField(default=None, max_length=2048),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='key_gen',
            name='machine',
            field=models.CharField(choices=[('nord3.bsc.es', 'nord3.bsc.es'), ('mn1.bsc.es', 'mn1.bsc.es'), ('power9login.bsc.es', 'power9login.bsc.es')], max_length=255),
        ),
    ]
