# Generated by Django 4.1.7 on 2024-02-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_execution_checkpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='checkpointBool',
            field=models.BooleanField(default=False),
        ),
    ]
