# Generated by Django 4.1.7 on 2023-04-19 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0007_key_gen_wdir_alter_key_gen_machine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='key_gen',
            name='user',
        ),
        migrations.RemoveField(
            model_name='key_gen',
            name='wdir',
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('fqdn', models.CharField(max_length=255)),
                ('wdir', models.CharField(max_length=2048)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.AlterField(
            model_name='key_gen',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.machine'),
        ),
    ]
