# Generated by Django 4.1.7 on 2023-05-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_key_gen_user_remove_key_gen_wdir_machine_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workflow',
            old_name='sensitivityType',
            new_name='sensitivity',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='output_folder',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='templateFile',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='wdir',
        ),
        migrations.AddField(
            model_name='execution',
            name='checkpoint',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='execution',
            name='execution_time',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='execution',
            name='name_workflow',
            field=models.CharField(default=-1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workflow',
            name='mesh',
            field=models.CharField(default='ciao', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workflow',
            name='outputs',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workflow',
            name='templateSim',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workflow',
            name='samplerParameters',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='sensitivityOutput',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='simulation',
            field=models.CharField(choices=[('alya', 'Alya')], default='alya', max_length=255),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='variablesFixed',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='variablesSampler',
            field=models.CharField(max_length=500),
        ),
    ]
