# Generated by Django 4.1.7 on 2023-05-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_sensitivitytype_workflow_sensitivity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='qos',
            field=models.CharField(default=-1, max_length=255),
            preserve_default=False,
        ),
    ]
