# Generated by Django 4.1.7 on 2024-06-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_execution_branch_execution_d_bool_execution_g_bool_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='project_name',
            field=models.CharField(default='bsc19', max_length=255),
        ),
    ]
